# Generated by Django 3.0.5 on 2020-05-04 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Puesto')),
                ('education', models.CharField(max_length=100, verbose_name='Escolaridad')),
                ('experience', models.CharField(max_length=100, verbose_name='Experiencia')),
                ('age', models.CharField(max_length=100, verbose_name='Edad')),
                ('languages', models.CharField(max_length=100, verbose_name='Idiomas')),
                ('knowledge', models.TextField(verbose_name='Conocimientos')),
                ('activities', models.TextField(verbose_name='Actividades')),
                ('travel', models.BooleanField()),
                ('places', models.CharField(max_length=100, verbose_name='Número de plazas')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'vacante',
                'verbose_name_plural': 'vacantes',
                'ordering': ['-created'],
            },
        ),
    ]
