# Generated by Django 3.0.5 on 2020-05-06 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='travel',
            field=models.BooleanField(verbose_name='Disponibilidad para viajar'),
        ),
    ]
