# Generated by Django 3.0.5 on 2020-05-14 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200506_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='activities',
            field=ckeditor.fields.RichTextField(verbose_name='Actividades'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='knowledge',
            field=ckeditor.fields.RichTextField(verbose_name='Conocimientos'),
        ),
    ]
